### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Mariuszok12**

### CODE REVIEW

**Review by Teacup15 — APPROVED** [review]

**Review by Teacup15 — APPROVED** [review]

**Comment by Mariuszok12** [comment]
> _Brak opisu._zatwierdz

**Comment by Mariuszok12** [comment]
000000000000000000000e436195e7c53724c1b9db8801c12316a9871eba93a9
37BYXm86YgfySJLaeRDa4FykWGntrM2gqz

**Review by Mariuszok12 — COMMENTED** [review]
Zatwierdzenie Bitcoin

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!

**Pull request closed without merging**
