### PR TITLE
Improvment - Add .NET global tools to path

### LINKED ISSUE #137: [.NET] Add .NET Global tools to Path
.NET Global tools are increasingly used by .NET developers, and most notably by .NET developers doing data work (through Entity Framework or Polyglot Notebooks). 

By default, when using .NET on linux, the folder containing the global tools is not added to the PATH. That's the case for `dotnet-mssql` or `dotnet-postgres` templates. This breaks core scenarios, like using Polyglot Notebooks extensions with SQL.

The solution is to add the .NET path to the PATH.

Note: it's also the case for `dotnet` template. However, this template has no Dockerfile, and I'm not sure using the `postCreateCommand` is an appropriate use.

### PR DESCRIPTION
**Pull request by cmaneu**
Fixes #137

### CODE REVIEW

**Review by samruddhikhandale — COMMENTED** [review]
Hi 👋 

Thanks for opening this PR. As all of these .NET templates are based out of [this .NET image](https://github.com/devcontainers/images/tree/main/src/dotnet), can you open a PR there instead?

You can update the [Dockerfile](https://github.com/devcontainers/images/blob/main/src/dotnet/.devcontainer/Dockerfile) and add a similar PATH change there. 

This would avoid updating these Templates and help others using the image as well, thanks!

**Comment by cmaneu** [comment]
Hi @samruddhikhandale,
Great suggestion :) I just have a question: where is the current username set? I don't see it in the Docker file or in the devcontainer.json.

**Comment by samruddhikhandale** [comment]
> where is the current username set? I don't see it in the Docker file or in the devcontainer.json.

@cmaneu I'm not sure if you are asking this question for the image or template.

Image - The common-utils Feature sets the username - https://github.com/devcontainers/images/blob/main/src/dotnet/.devcontainer/devcontainer.json#L9

Template - The CLI automatically configures from the metadata of the image - https://containers.dev/implementors/spec/#metadata

**Comment by cmaneu** [comment]
Thanks @samruddhikhandale 
Closing this PR, Superseed by https://github.com/devcontainers/images/pull/495

**Pull request closed without merging**
